# Generated by Django 4.1.5 on 2023-01-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
