# Generated by Django 4.1.5 on 2023-02-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0002_historicalorganization_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='kind',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SUPPLIER', 'Supplier'), ('RETAILER', 'Retailer'), ('ARCHITECT', 'Architect'), ('INTERIOR_DESIGNER', 'Interior Designer'), ('FURNITURE_DESIGNER', 'Furniture Designer'), ('PROJECT_MANAGER', 'Project Manager'), ('CARPENTER', 'Carpenter'), ('PAINTER', 'Painter'), ('TAILOR', 'Tailor'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('OTHER', 'Other')], db_index=True, default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLACEHOLDER', 'Placeholder'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SUPPLIER', 'Supplier'), ('RETAILER', 'Retailer'), ('ARCHITECT', 'Architect'), ('INTERIOR_DESIGNER', 'Interior Designer'), ('FURNITURE_DESIGNER', 'Furniture Designer'), ('PROJECT_MANAGER', 'Project Manager'), ('CARPENTER', 'Carpenter'), ('PAINTER', 'Painter'), ('TAILOR', 'Tailor'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('OTHER', 'Other')], db_index=True, default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLACEHOLDER', 'Placeholder'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
