# Generated by Django 4.2.1 on 2023-06-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0004_historicalorganization_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='kind',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SUPPLIER', 'Supplier'), ('RETAILER', 'Retailer'), ('SERVICE_PROVIDER', 'Service Provider'), ('OTHER', 'Other')], db_index=True, default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SUPPLIER', 'Supplier'), ('RETAILER', 'Retailer'), ('SERVICE_PROVIDER', 'Service Provider'), ('OTHER', 'Other')], db_index=True, default='UNKNOWN', max_length=20),
        ),
    ]
