# Generated by Django 4.1.7 on 2023-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0005_alter_historicalorganization_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='designation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
