# Generated by Django 4.1.7 on 2023-08-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0006_organizationuser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
