# Generated by Django 4.1.7 on 2023-08-03 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0012_historicalproduct_channels_product_channels'),
        ('notificationio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogio.productbrand'),
        ),
        migrations.AddField(
            model_name='notification',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogio.service'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='new_brand',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='new_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='turn_off_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('EVENT_POST', 'Event Post'), ('GROUP_INVITE_REQUEST', 'Group Invite Request'), ('GROUP_INVITE_ACCEPTED', 'Group Invite Accepted'), ('GROUP_INVITE_REJECTED', 'Group Invite Rejected'), ('INVITE_REQUEST', 'Invite Request'), ('INVITE_ACCEPTED', 'Invite Accepted'), ('INVITE_REJECTED', 'Invite Rejected'), ('NEW_BRAND', 'New Brand'), ('NEW_PRODUCT', 'New Product'), ('NEW_PROJECT', 'New Project'), ('NEWS_POST', 'News Post'), ('NEW_SERVICE', 'New Service'), ('POST_REPLY', 'Post Reply'), ('POST_LIKE', 'Post Like'), ('PRODUCT_PRICING', 'Product Pricing'), ('FILE', 'File')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='model_kind',
            field=models.CharField(choices=[('BRAND', 'Brand'), ('PRODUCT', 'Product'), ('PROJECT', 'Project'), ('ORGANIZATION_INVITE', 'Organization Invite'), ('MEMBER', 'Member'), ('NEWS_DESK_POST', 'News Desk Post'), ('PRODUCT_DISCOUNT', 'Product Discount'), ('FILE_ITEM_ACCESS', 'File Item Access'), ('SERVICE', 'Service')], db_index=True, max_length=20),
        ),
    ]
