from django.urls import path

from catalogio.rest.views.partners_services import GlobalPartnerServiceList

from ..views import (
    organizations,
    organizations_brands,
    organizations_groups,
    organizations_news,
    organizations_products,
    organizations_projects,
    organizations_users,
    organizations_files,
    organizations_showroom,
    organizations_images,
    organizations_invitation,
)

urlpatterns = [
    path(
        r"/onboarding",
        organizations.PublicOrganizationOnboardingDetail.as_view(),
        name="organizations.onboarding-detail",
    ),
    path(
        r"/<slug:organization_slug>/users",
        organizations_users.PublicOrganizationUserList.as_view(),
        name="organizations.organization_users-list",
    ),
    path(
        r"/<slug:organization_slug>/users/<slug:slug>",
        organizations_users.PublicOrganizationUserDetail.as_view(),
        name="organizations.organization_user-detail",
    ),
    path(
        r"/<slug:organization_slug>/brands",
        organizations_brands.PublicOrganizationBrandList.as_view(),
        name="organizations.brand-list",
    ),
    path(
        "/<slug:slug>/groups",
        organizations_groups.PublicOrganizationGroupList.as_view(),
        name="organizations.organization_groups-list",
    ),
    path(
        r"/<slug:organization_slug>/groups/<slug:group_slug>",
        organizations_groups.PublicOrganizationGroupDetail.as_view(),
        name="organizations.organization_group-detail",
    ),
    path(
        r"/<slug:slug>/products",
        organizations_products.PublicOrganizationProductList.as_view(),
        name="organizations.products-list",
    ),
    path(
        r"/<slug:organization_slug>/products/<slug:slug>",
        organizations_products.PublicOrganizationProductDetail.as_view(),
        name="organizations.product-detail",
    ),
    path(
        r"/<slug:organization_slug>/products/<slug:slug>/images",
        organizations_products.PublicOrganizationProductImageList.as_view(),
        name="organizations.product_image-list",
    ),
    path(
        r"/<slug:organization_slug>/images",
        organizations_images.PublicImageList.as_view(),
        name="organizations.organization_image-list",
    ),
    path(
        r"/<slug:organization_slug>/images/<uuid:image_uid>",
        organizations_images.PublicImageDetail.as_view(),
        name="organizations.organization_image-detail",
    ),
    path(
        r"/<slug:organization_slug>/news",
        organizations_news.PublicOrganizationNewsList.as_view(),
        name="organizations.news-list",
    ),
    path(
        r"/<slug:organization_slug>/news/<slug:post_slug>",
        organizations_news.PublicOrganizationNewsDetail.as_view(),
        name="organizations.news-detail",
    ),
    path(
        r"/by/projects",
        organizations.PublicOrganizationListByProject.as_view(),
        name="organizations.organization-by-project",
    ),
    path(
        r"/<slug:organization_slug>/projects",
        organizations_projects.PublicOrganizationProjectList.as_view(),
        name="organizations.projects-list",
    ),
    path(
        r"/<slug:organization_slug>/projects/<slug:project_slug>",
        organizations_projects.PublicOrganizationProjectDetail.as_view(),
        name="organizations.project-detail",
    ),
    path(
        r"/<slug:organization_slug>/files",
        organizations_files.PublicFileItemList.as_view(),
        name="organizations.file_items-list",
    ),
    path(
        r"/<slug:organization_slug>/files/<uuid:file_uid>",
        organizations_files.PublicFileItemDetail.as_view(),
        name="organizations.file_item-detail",
    ),
    path(
        r"/<slug:organization_slug>/showroom",
        organizations_showroom.PublicOrganizationShowroomList.as_view(),
        name="organizations.showroom-list",
    ),
    path(
        r"/<slug:slug>/partner-services",
        GlobalPartnerServiceList.as_view(),
        name="organizations.partner-service-list",
    ),
    path(
        r"/<slug:slug>/invites",
        organizations_invitation.PublicOrganizationPartnerInvitation.as_view(),
        name="organizations.partner-invite",
    ),
    path(
        r"/<slug:slug>",
        organizations.PublicOrganizationDetail.as_view(),
        name="organizations.organization-detail",
    ),
    path(
        r"",
        organizations.PublicOrganizationList.as_view(),
        name="organizations.organizations-list",
    ),
]
