# Generated by Django 4.2.1 on 2023-06-19 08:24

import autoslug.fields
import contentio.utils
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountio', '0005_alter_historicalorganization_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=contentio.utils.get_faq_slug, unique=True)),
                ('segment', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=contentio.utils.get_faq_media_path_prefix)),
                ('youtube_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number is higher priority.')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=contentio.utils.get_customer_service_slug, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=contentio.utils.get_organization_media_path_prefix)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('ARCHIVED', 'Archived'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountio.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
