# Generated by Django 4.1.5 on 2023-01-23 21:10

import autoslug.fields
import collabio.slugifiers
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mediaroomio.paths
import simple_history.models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogio', '0001_initial'),
        ('collabio', '0002_alter_historicalproject_organization_slug_and_more'),
        ('gruppio', '0001_initial'),
        ('accountio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsdeskio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to=mediaroomio.paths.get_mediaimage_image_path, width_field='width')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('copyright', models.CharField(blank=True, max_length=100)),
                ('priority', models.BigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], db_index=True, max_length=20)),
                ('organization_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountio.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMediaImageConnector',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('kind', models.CharField(choices=[('UNDEFINED', 'Undefined'), ('GROUP', 'Group'), ('NEWSPOST', 'News Post'), ('PRODUCT', 'Product'), ('PROJECT', 'Project')], db_index=True, default='UNDEFINED', max_length=20)),
                ('organization_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gruppio.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mediaroomio.mediaimage')),
                ('newspost', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='newsdeskio.newsdeskpost')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountio.organization')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogio.product')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collabio.project')),
            ],
            options={
                'verbose_name': 'historical media image connector',
                'verbose_name_plural': 'historical media image connectors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMediaImage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('image', models.TextField(max_length=100)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('copyright', models.CharField(blank=True, max_length=100)),
                ('priority', models.BigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], db_index=True, max_length=20)),
                ('organization_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountio.organization')),
            ],
            options={
                'verbose_name': 'historical media image',
                'verbose_name_plural': 'historical media images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MediaImageConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('UNDEFINED', 'Undefined'), ('GROUP', 'Group'), ('NEWSPOST', 'News Post'), ('PRODUCT', 'Product'), ('PROJECT', 'Project')], db_index=True, default='UNDEFINED', max_length=20)),
                ('organization_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gruppio.group')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaroomio.mediaimage')),
                ('newspost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsdeskio.newsdeskpost')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountio.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.product')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collabio.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('image', 'project'), ('image', 'newspost'), ('image', 'product'), ('image', 'group')},
                'index_together': {('image', 'project'), ('image', 'newspost'), ('image', 'product'), ('image', 'group')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
