# Generated by Django 4.1.7 on 2023-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaroomio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmediaimage',
            name='spot',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'Undefined'), ('SHOWROOM', 'Showroom')], default='UNDEFINED', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmediaimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='spot',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'Undefined'), ('SHOWROOM', 'Showroom')], default='UNDEFINED', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
