# Generated by Django 4.1.7 on 2023-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaroomio', '0002_historicalmediaimage_spot_historicalmediaimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmediaimage',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], db_index=True, default='PUBLISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], db_index=True, default='PUBLISHED', max_length=20),
        ),
    ]
