# Generated by Django 4.1.7 on 2023-06-18 11:16

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0005_alter_historicalorganization_kind_and_more'),
        ('mediaroomio', '0003_historicalmediaimage_status_mediaimage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowRoomImageConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='mediaroomio.mediaimage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_image', to='mediaroomio.mediaimage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountio.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('image', 'gallery_image')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
