# Generated by Django 4.1.3 on 2023-01-06 15:13

import autoslug.fields
import collabio.slugifiers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='organization_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_project_slug),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_project_slug, unique=True),
        ),
    ]
