# Generated by Django 4.1.7 on 2023-05-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabio', '0002_alter_historicalproject_organization_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectparticipant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
