# Generated by Django 4.1.7 on 2023-08-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabio', '0003_alter_historicalprojectparticipant_status_and_more'),
        ('paymentio', '0001_initial'),
        ('accountio', '0006_organizationuser_designation'),
        ('catalogio', '0013_remove_service_organization_service_kind_and_more'),
        ('adio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adorganization',
            name='adfeature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paymentio.adfeature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adorganization',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountio.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adproduct',
            name='adfeature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paymentio.adfeature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adproduct',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountio.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogio.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adproject',
            name='adfeature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paymentio.adfeature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adproject',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountio.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adproject',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collabio.project'),
            preserve_default=False,
        ),
    ]
