# Generated by Django 4.1.7 on 2023-05-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdeskio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnewsdeskpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsdeskpost',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
