# Generated by Django 4.1.7 on 2023-08-02 05:57

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0006_organizationuser_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsdeskio', '0002_historicalnewsdeskpost_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPostAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PARTNER', 'Partner'), ('USER', 'User')], default='PARTNER', max_length=20)),
                ('newspost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsdeskio.newsdeskpost')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountio.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('newspost', 'partner'), ('newspost', 'user')},
                'index_together': {('newspost', 'partner'), ('newspost', 'user')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
