from django.urls import include, path

urlpatterns = [
    path("/ads", include("weapi.rest.urls.ads")),
    path("/brands", include("weapi.rest.urls.brands")),
    path("/collections", include("weapi.rest.urls.collections")),
    path("/customer-services", include("weapi.rest.urls.customer_services")),
    path("/dashboard", include("weapi.rest.urls.dashboard")),
    path("/files", include("weapi.rest.urls.files")),
    path("/groups", include("weapi.rest.urls.groups")),
    path("/images", include("weapi.rest.urls.mediaroom")),
    path("/inbox", include("weapi.rest.urls.inbox")),
    path("/invites", include("weapi.rest.urls.invites")),
    path("/materials", include("weapi.rest.urls.materials")),
    path("/my-organizations", include("weapi.rest.urls.organizations")),
    path("/news", include("weapi.rest.urls.news")),
    path("/notification-settings", include("weapi.rest.urls.notifications")),
    path("/partners", include("weapi.rest.urls.partners")),
    path("/plans", include("weapi.rest.urls.subscription_session")),
    path("/products", include("weapi.rest.urls.products")),
    path("/projects", include("weapi.rest.urls.projects")),
    path("/search", include("weapi.rest.urls.search")),
    path("/services", include("weapi.rest.urls.service")),
    path("/showroom", include("weapi.rest.urls.showroom")),
    path("/status", include("weapi.rest.urls.status")),
    path("/tags", include("weapi.rest.urls.tags")),
    path("/transactions", include("weapi.rest.urls.subscription_transaction")),
    path("/users", include("weapi.rest.urls.users")),
    path("", include("weapi.rest.urls.we")),
]
