# Generated by Django 4.1.3 on 2023-01-12 21:54

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('organization_no', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=40)),
                ('postal_area', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('UNTOUCHED', 'Untouched'), ('CONTACTED', 'Contacted'), ('UNAVAILABLE', 'Unavailable'), ('WRONG_NUMBER', 'Wrong Number'), ('NOT_INTERESTED', 'Not Interested'), ('INTERESTED', 'Interested'), ('FOLLOW_UP', 'Follow Up'), ('CLOSED', 'Closed')], default='UNTOUCHED', max_length=20)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadio.potentiallead')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPotentialLead',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('organization_no', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=40)),
                ('postal_area', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('UNTOUCHED', 'Untouched'), ('CONTACTED', 'Contacted'), ('UNAVAILABLE', 'Unavailable'), ('WRONG_NUMBER', 'Wrong Number'), ('NOT_INTERESTED', 'Not Interested'), ('INTERESTED', 'Interested'), ('FOLLOW_UP', 'Follow Up'), ('CLOSED', 'Closed')], default='UNTOUCHED', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical potential lead',
                'verbose_name_plural': 'historical potential leads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
