# Generated by Django 4.1.3 on 2023-01-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leadio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="potentiallead",
            options={"ordering": ("name",)},
        ),
    ]
