# Generated by Django 4.1.5 on 2023-01-23 21:12

import autoslug.fields
import collabio.slugifiers
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fileroomio.paths
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruppio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountio', '0001_initial'),
        ('collabio', '0002_alter_historicalproject_organization_slug_and_more'),
        ('catalogio', '0001_initial'),
        ('newsdeskio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fileitem', models.FileField(upload_to=fileroomio.paths.get_fileitem_file_path)),
                ('size', models.PositiveIntegerField(default=0)),
                ('dotextension', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PRICE_LIST', 'Price List'), ('BROCHURE', 'Brochure')], max_length=20)),
                ('extension', models.CharField(choices=[('EXCEL', 'Excel'), ('POWERPOINT', 'Powerpoint'), ('WORD', 'Word'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('OTHER', 'Other')], max_length=20)),
                ('visibility', models.CharField(choices=[('SECRET', 'Secret'), ('PRIVATE', 'Private'), ('PUBLIC', 'Public')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('REMOVED', 'Removed')], max_length=20)),
                ('organization_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountio.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFileItemConnector',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('kind', models.CharField(choices=[('UNDEFINED', 'Undefined'), ('GROUP', 'Group'), ('NEWS_POST', 'News Post'), ('PRODUCT', 'Product'), ('PROJECT', 'Project')], db_index=True, default='UNDEFINED', max_length=20)),
                ('organization_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fileitem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fileroomio.fileitem')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gruppio.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('newspost', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='newsdeskio.newsdeskpost')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountio.organization')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogio.product')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collabio.project')),
            ],
            options={
                'verbose_name': 'historical file item connector',
                'verbose_name_plural': 'historical file item connectors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFileItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('fileitem', models.TextField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('dotextension', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PRICE_LIST', 'Price List'), ('BROCHURE', 'Brochure')], max_length=20)),
                ('extension', models.CharField(choices=[('EXCEL', 'Excel'), ('POWERPOINT', 'Powerpoint'), ('WORD', 'Word'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('OTHER', 'Other')], max_length=20)),
                ('visibility', models.CharField(choices=[('SECRET', 'Secret'), ('PRIVATE', 'Private'), ('PUBLIC', 'Public')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('REMOVED', 'Removed')], max_length=20)),
                ('organization_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accountio.organization')),
            ],
            options={
                'verbose_name': 'historical file item',
                'verbose_name_plural': 'historical file items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FileItemConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('UNDEFINED', 'Undefined'), ('GROUP', 'Group'), ('NEWS_POST', 'News Post'), ('PRODUCT', 'Product'), ('PROJECT', 'Project')], db_index=True, default='UNDEFINED', max_length=20)),
                ('organization_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=collabio.slugifiers.get_organization_slug)),
                ('fileitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileroomio.fileitem')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gruppio.group')),
                ('newspost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsdeskio.newsdeskpost')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountio.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogio.product')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collabio.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('fileitem', 'newspost'), ('fileitem', 'group'), ('fileitem', 'product'), ('fileitem', 'project')},
                'index_together': {('fileitem', 'newspost'), ('fileitem', 'group'), ('fileitem', 'product'), ('fileitem', 'project')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
