# Generated by Django 4.1.7 on 2023-04-29 02:04

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accountio", "0004_historicalorganization_county_and_more"),
        ("fileroomio", "0002_alter_fileitem_kind_alter_historicalfileitem_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileitem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalfileitem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fileitem",
            name="extension",
            field=models.CharField(
                choices=[
                    ("EXCEL", "Excel"),
                    ("POWERPOINT", "Powerpoint"),
                    ("WORD", "Word"),
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fileitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("PRICE_LIST", "Price List"),
                    ("BROCHURE", "Brochure"),
                    ("CATALOG", "Catalog"),
                    ("PRODUCT_INFORMATION", "Product Information"),
                    ("DRAWING", "Drawing"),
                    ("CERTIFICATE", "Certificate"),
                    ("CARE_INSTRUCTION", "Care Instruction"),
                    ("PRESS", "Press"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfileitem",
            name="extension",
            field=models.CharField(
                choices=[
                    ("EXCEL", "Excel"),
                    ("POWERPOINT", "Powerpoint"),
                    ("WORD", "Word"),
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfileitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("PRICE_LIST", "Price List"),
                    ("BROCHURE", "Brochure"),
                    ("CATALOG", "Catalog"),
                    ("PRODUCT_INFORMATION", "Product Information"),
                    ("DRAWING", "Drawing"),
                    ("CERTIFICATE", "Certificate"),
                    ("CARE_INSTRUCTION", "Care Instruction"),
                    ("PRESS", "Press"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FileItemAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("PARTNER", "Partner"), ("USER", "User")],
                        default="PARTNER",
                        max_length=20,
                    ),
                ),
                (
                    "fileitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fileroomio.fileitem",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accountio.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("fileitem", "partner"), ("fileitem", "user")},
                "index_together": {("fileitem", "partner"), ("fileitem", "user")},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
