# Generated by Django 4.1.7 on 2023-03-27 19:52

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountio', '0003_alter_historicalorganization_kind_and_more'),
        ('catalogio', '0002_historicalproduct_categories_historicalproduct_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent'), ('NET_PRICE', 'Net Price')], default='PERCENT', max_length=20)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=20)),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountio.organization')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='accountio.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'target', 'category')},
                'index_together': {('organization', 'target', 'category')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
