# Generated by Django 4.1.7 on 2023-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0003_productdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='external_url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='scraped',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='scraped',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='kind',
            field=models.CharField(choices=[('DISCOUNT', 'Discount'), ('NET_PRICE', 'Net Price')], default='DISCOUNT', max_length=20),
        ),
    ]
