# Generated by Django 4.1.7 on 2023-04-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0004_historicalproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='scraped',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='scraped',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
