# Generated by Django 4.1.7 on 2023-07-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogio', '0011_material_productmaterialconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='channels',
            field=models.CharField(choices=[('OWN_CHANNEL', 'Own Channel'), ('PARTNERS_CHANNELS', 'Partners Channels'), ('ALL_CHANNELS', 'All Channels')], default='OWN_CHANNEL', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='channels',
            field=models.CharField(choices=[('OWN_CHANNEL', 'Own Channel'), ('PARTNERS_CHANNELS', 'Partners Channels'), ('ALL_CHANNELS', 'All Channels')], default='OWN_CHANNEL', max_length=30),
        ),
    ]
